package com.zhengzhengyiyimc;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;

public class PythonScriptManager {
    private static final String PYTHON_SCRIPT = """
# generated by zhengzhengyiyimc

import ollama
from argparse import ArgumentParser

def ask_ollama(prompt):
    response = ollama.chat(
        model="tinyllama",
        # format="json",
        messages=[
            {"role": "system", "content": f"You are an AI assisstant in Minecraft {version} by using a Minecraft JAVA mod, your name is ollama. Please answer it detaily. Try to get the point of the question, using simple language, and make your answer short. Do not talk about Minecraft download, and only talk about Minecraft."},
            {"role": "user", "content": prompt}
        ],
    )
    return response["message"]["content"]

if __name__ == '__main__':
    parser = ArgumentParser("Run pretrained models on MineRL environment")

    parser.add_argument("--version", type=str, required=True, help="pass into the Minecraft version")
    parser.add_argument("--prompt", type=str, required=True, help="the thing that need to ask to ai")

    args = parser.parse_args()

    version = args.version
    prompt = args.prompt

    print(ask_ollama(prompt), flush=True)
""";

    public static void ensurePythonScriptExists(Path scriptPath) throws IOException {
        Files.createDirectories(scriptPath.getParent());
        
        Files.writeString(
            scriptPath, 
            PYTHON_SCRIPT,
            StandardOpenOption.CREATE_NEW
        );
        
        System.out.println("python script made in: " + scriptPath);
    }

    public static boolean checkScriptExists(Path scriptPath) {
        return Files.exists(scriptPath) && Files.isRegularFile(scriptPath);
    }
}